### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by abhishekraok** [abisee/pointer-generator#10]
Hi, 
Is it possible to add an open source license? Something like MIT License?
Thanks

**Comment by boyTerry** [comment]
I would recommend @abisee adds a license file ASAP

Terms of service accepted by posting it to git hub:

... By setting your repositories to be viewed publicly, you agree to allow others to view and fork your repositories. ...

@abhishekraok If you are worried about a restrictive licence, I would fork now.

**Comment by abisee** [comment]
Thanks for bringing this to my attention @abhishekraok @boyTerry, am figuring this out right now and will add a license soon.

**Comment by abisee** [comment]
Done.

**Comment by abhishekraok** [comment]
Thank you very much
