### ISSUE TITLE
The rouge-L result is very low

### ISSUE THREAD

**Issue by hanghang2333** [abisee/pointer-generator#106]
I am working on a model of a text summary. For the output of the model, the test is performed using pyrouge. The test results show that the rouge-1 and rouge2 indicators are normal and consistent with the effect of the paper. However, the results of rouge-L differ greatly from the results of the paper. What is doubtful is how the rouge-L is calculated. What could be the cause of this?

**Comment by lipiji** [comment]
HI, did you know the reason of low R-L?
