### ISSUE TITLE
'NoneType' object has no attribute 'enc_batch'

### ISSUE THREAD

**Issue by sarmnoo** [abisee/pointer-generator#11]
when I run the train model, the problem happened after several training steps,about 300 steps,i have no idea about this problem..

this is the problem:
feed_dict = self._make_feed_dict(batch)
  File "/users2/ddning/parapharse_generation/pointer-generator/pointer-generator-master/model.py", line 49, in _make_feed_dict
    feed_dict[self._enc_batch] = batch.enc_batch 
AttributeError: 'NoneType' object has no attribute 'enc_batch'

**Comment by abisee** [comment]
Are you running in train mode? Have you set the flag `single_pass` to True?

**Comment by sarmnoo** [comment]
yes, I'm running in train mode, and the single_pass is True.

**Comment by abisee** [comment]
That's the problem. The `single_pass` flag [is for decode mode only](https://github.com/abisee/pointer-generator/blob/master/run_summarization.py#L39). 

When `single_pass=True`, you run through the data in order, exactly once. This is useful in decode mode if you want to produce summaries for each example in the test set. But for training, you want to loop randomly through the data indefinitely, i.e. `single_pass=False` (so leave it as the default `False`).

Hope this clarifies things.

**Comment by sarmnoo** [comment]
ok, I got it, thank you so much!😊
