### ISSUE TITLE
Building Graph: std::bad_alloc

### ISSUE THREAD

**Issue by pltrdy** [abisee/pointer-generator#13]
I'm trying to run your code using another dataset tokenized/bin as in your CNN/DM repo. 
I'm running it using 32Go RAM & Nvidia 1080.

It looks memory related so I tried to set small values for some parameters and still got the issue.

## Command

`python run_summarization.py --mode train --data_path ./data/train.bin --vocab_path ./data/vocab  --log_root ./ --exp_name cnndm_summ --batch_size 4 --vocab_size 25000 --max_enc_steps 200 --max_dec_steps 100`

## Output

```
[...]
INFO:tensorflow:Adding attention_decoder timestep 80 of 100
INFO:tensorflow:Adding attention_decoder timestep 81 of 100
INFO:tensorflow:Adding attention_decoder timestep 82 of 100
INFO:tensorflow:Adding attention_decoder timestep 83 of 100
INFO:tensorflow:Adding attention_decoder timestep 84 of 100
INFO:tensorflow:Adding attention_decoder timestep 85 of 100
INFO:tensorflow:Adding attention_decoder timestep 86 of 100
INFO:tensorflow:Adding attention_decoder timestep 87 of 100
INFO:tensorflow:Adding attention_decoder timestep 88 of 100
INFO:tensorflow:Adding attention_decoder timestep 89 of 100
INFO:tensorflow:Adding attention_decoder timestep 90 of 100
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
max_size of vocab was specified as 25000; we now have 25000 words. Stopping reading.
Finished constructing vocabulary of 25000 total words. Last word added: pencils
creating model...
Writing word embedding metadata file to ./cnndm_summ/train/vocab_metadata.tsv...
```

If you have any clue/advice

Thx for releasing the code, paper & blog post btw

**Comment by abisee** [comment]
Hi @pltrdy, I've never seen this `std::bad_alloc` error before. After googling the error, the advice does seem memory related. Sorry not be of more help!

**Comment by pltrdy** [comment]
The issue was on my side (the dataset).

Closing the issue. thx for fast answer tho.

**Comment by alyaxey** [comment]
@pltrdy Hi! I have the same problem. Could you please tell me what was the cause in your case?
