### ISSUE TITLE
Is it normal that, for every decoding step, pgen is the same for all the inputs in the batch?

### ISSUE THREAD

**Issue by gionapaolini** [abisee/pointer-generator#134]
I am trying to understand how the pgens are computed. 
My first guess was that, for each decoding step, we would get a different pgen for each input in the batch.
But from the code I noticed instead that the entire batch shares the same pgen for each decoding step.

    for i, inp in enumerate(decoder_inputs):  # decoder_inputs is a list of 2D Tensors [batch_size x input_size].
      
         ...

         # Calculate p_gen
         if pointer_gen:
             with tf.variable_scope('calculate_pgen'):
             p_gen = linear([context_vector, state.c, state.h, x], 1, True) # a scalar
             p_gen = tf.sigmoid(p_gen)
             print(p_gen.shape)
             p_gens.append(p_gen)

Can someone clarify this to me?
Is it supposed to be like this? Or am I missing something?

**Comment by gionapaolini** [comment]
Ops, it's actually working as expected, I was missing few things, closing the issue

**Comment by pig60214** [comment]
hello gionapaolini, can I know what you miss to cause this situation? Thanks.
