### ISSUE TITLE
what's the meaning of this code?

### ISSUE THREAD

**Issue by policeme** [abisee/pointer-generator#139]
@abisee could you tell me the meaning of this code?
![image](https://user-images.githubusercontent.com/30991932/56492540-b2851080-651e-11e9-9fbb-849b2e8e7e9b.png)

**Comment by policeme** [comment]
or anyone can tell me the meaning, thx.

**Comment by policeme** [comment]
![image](https://user-images.githubusercontent.com/30991932/56494316-689f2900-6524-11e9-8d10-e6a27fa4c5ca.png)
and this code

**Comment by peixin-lin** [comment]
Hi, I am also confused about this part, especially the shape of the inputs of the attention score. Did you figure this part out?

**Comment by xiongma** [comment]
no, it passed one year!
