### ISSUE TITLE
FLAGS.pointer_gen in data.py 

### ISSUE THREAD

**Issue by makcbe** [abisee/pointer-generator#17]
When data.py encounters a word id that is not in vocabulary, the program terminates as the FLAGS is not defined.
`assert FLAGS.pointer_gen, "Error: model produced a word ID that isn't in the vocabulary"`

Adding below lines solves the problem

```
import tensorflow as tf

FLAGS = tf.app.flags.FLAGS
```

**Comment by pltrdy** [comment]
This has been fixed in b9c9cc07d6840b83d21bdf9fe8e364b7446334ed.

You should `git pull` the repo to update.
