### ISSUE TITLE
When are the attention probabilities for repeated indices summed?

### ISSUE THREAD

**Issue by Henry-E** [abisee/pointer-generator#29]
From the paper 

> When a word appears multiple times in the source text, we sum probability mass from all corresponding parts of the attention distribution

However I wasn't able to find the part of the code that sums up the probability mass when an index appears multiple times in the encoder. As used in [this](https://github.com/abisee/pointer-generator/blob/master/model.py#L174) line tf.scatter_nd doesn't apply a summation when there are repeated indices. And I can't see a point [earlier in the code](https://github.com/abisee/pointer-generator/blob/master/attention_decoder.py#L103) where this operation is performed. I only ask such a detailed question because I'm trying to implement the copy mechanism and this is a particularly tricky part to do without messing up the autograd mechanics in pytorch.

**Comment by Henry-E** [comment]
Pytorch now has a scatter_add function which handles this issue quite nicely

**Comment by abisee** [comment]
See [this discussion](https://github.com/abisee/pointer-generator/issues/22) about `tf.scatter_nd`
