### ISSUE TITLE
Failed to load checkpoint on eval mode

### ISSUE THREAD

**Issue by acohan** [abisee/pointer-generator#31]
I am trying to run `mode=train` and concurrently run another instance with `mode=eval`. 
However, on the `eval` part I am getting the following errors:

```
2017-07-20 12:19:30.099613: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match.
lhs shape= [50000,128] rhs shape= [4,128]
         [[Node: save/Assign_13 = Assign[T=DT_FLOAT, _class=["loc:@seq2seq/embedding/embedding"], use_locking=true, validate_shape=true,
          _device="/job:localhost/replica:0/task:0/gpu:0"](seq2seq/embedding/embedding, save/RestoreV2_13/_49)]]
INFO:tensorflow:Failed to load checkpoint from ./log/testexp/train. Sleeping for 10 secs...

File "util.py", line 41, in load_ckpt
```

Any idea what could be the reason?

**Comment by eduOS** [comment]
I just put the best checkpoint from eval directory to a new train directory. It works.

**Comment by acohan** [comment]
Right. I was also able to resolve this with re-training the model. Not sure what was the source of error.

**Comment by saketdingliwal** [comment]
Please check the vocab file in the finished_files. For pretrained model to work, it requires a vocab size of 50000 to load. One might not be using the vocab file from CNN dataset and hence the size mismatch while loading the checkpoint
