### ISSUE TITLE
Problem of the word embedding of OOV words of decoder inputs

### ISSUE THREAD

**Issue by rylanchiu** [abisee/pointer-generator#32]
Hi, I have some difficulties on understanding your code, in particular, the [word embedding of the decoder input](https://github.com/abisee/pointer-generator/blob/master/model.py#L212). As for the `emb_enc_inputs`, it uses the source input with all the OOV words replaced by UNK tokens and that makes sense for me. But the `emb_dec_inputs` uses the target input with all the OOV words has a temporary id. Why do you use that for `embedding_lookup`? Please correct me if I had made any mistake. Thanks in advance!

**Comment by rylanchiu** [comment]
oh I see. Seems that just the `target` has OOV ids but `decoder_inputs` does not. Thanks.

**Comment by hashbangCoder** [comment]
If I get this correctly, words that are OOV and **do not** appear in the source article are mapped to UNK token?

So, a generated abstract can still produce an UNK output except it is rare?

**Comment by abisee** [comment]
@hashbangCoder 

All OOV words are represented by the UNK word embedding (encoder input and decoder input). In addition we assign temporary vocabulary IDs to all OOVs that appear in the source text. We have two versions of the encoder batch: 

* `enc_batch` [here](https://github.com/abisee/pointer-generator/blob/master/model.py#L40) represents each OOV with the vocabulary ID for UNK. This is needed for the [word embedding lookup](https://github.com/abisee/pointer-generator/blob/master/model.py#L211).
* `enc_batch_extended_vocab` [here](https://github.com/abisee/pointer-generator/blob/master/model.py#L43) represents each article OOV with its temporary vocabulary ID. This is needed to [compute the final distribution](https://github.com/abisee/pointer-generator/blob/master/model.py#L164).

The decoder can produce any word in the extended vocabulary: that's the vocabulary (which includes UNK) plus any in-article OOVs. So the decoder can produce an UNK but I don't see it happen in the pointer-generator model.

**Comment by lipiji** [comment]
@abisee   Could you please explain the generation process of a  in-article OOV word? Because these words have no generation-probability and attention-weights, so I can not understand how to make these words appear in the results during training and testing.

**Comment by abisee** [comment]
@lipiji 

>  Could you please explain the generation process of a in-article OOV word? Because these words have no generation-probability and attention-weights,

This isn't correct - an in-article OOV word can have non-zero attention weights, and that's how you can produce an in-article OOV word in the summary.

**Comment by lipiji** [comment]
@abisee   I see. Maybe the in-article OOV word information can be implied by the encoder hidden states.
