### ISSUE TITLE
After training how to summarize our own Text

### ISSUE THREAD

**Issue by kergann** [abisee/pointer-generator#43]

**Comment by chandu-siri** [comment]
@kergann Can you tell me how you did that ? I'm also having same issue. i.e. "Given a text file I need summary of that file". Should I convert that file to .bin format as done for training ?

**Comment by kergann** [comment]
Hello, 

If i correctly understood, in batcher.py, the article the full article in a string variable.
So you can just change it to whatever you want. article="your article"

I hope that will help you.

Best.

**Comment by Sharathnasa** [comment]
@kergann As you told there is article variable which needs to be replaced with our own string in batcher.py, what about the abstract_sentences? Do we need to specify this as well?

**Comment by dondon2475848** [comment]
Hi @chandra-siri ,
You can clone below repository:
[https://github.com/dondon2475848/make_datafiles_for_pgn](https://github.com/dondon2475848/make_datafiles_for_pgn)
Run
```
python make_datafiles.py  ./stories  ./output
```
It processes your test data into the binary format
