### ISSUE TITLE
Efficiently generate summaries from new data?

### ISSUE THREAD

**Issue by ibarrien** [abisee/pointer-generator#51]
How do folks typically generate summaries given i) new text files (only content, no headlines/abstracts/urls) and ii) the pretrained model?

It seems that make_datafiles.py from the cnn-dailymail dir needs to be modified (e.g. removing much of the hardcoding). After these modifications, make_datafiles.py may be used to tokenize and chunk the new data. From there, we "decode" using the pretrained model to generate new summaries.

Is the above generally correct or is there a more efficient method?

**Comment by ibarrien** [comment]
Tips for anyone running decoding on a pretrained model:
after tokenizing and chunking your text(s) as above, run a command like:

`python pointer-generator-master/run_summarization.py --mode=decode --data_path=/path/to/your/finished_test_files/chunked/test_* --vocab_path=vocab --log_root=/path/to/pretrained_model --exp_name=pretrained_model_ --coverage=1  --single_pass=1 --max_enc_steps=500 --max_dec_steps=200 --min_dec_steps 100`

Here, "vocab" is the from the "finished" cnn+daily mail data and "pretrained_model" is, e.g., one of the pretrained models kindly made available by the author.

The summarization results will then be located in a decoded folder "decode" inside a new folder of the sort "decode_test_500maxenc..."

**Comment by Sharathnasa** [comment]
@ibarrien What changes did you do in make_datafiles.py? In the cnn-dailymail code, input is fed in the form of urls, there how to give only as input and generate new data? Could you please shed some light?

**Comment by pruthvishetty** [comment]
If you are trying to test the model on your own data, you can avoid dealing with the `url_lists` folder altogether. You can follow this - https://github.com/dondon2475848/make_datafiles_for_pgn to generate bin file(s) for summarizing your data. Use it with --single_pass=1,  if you are testing individual articles, like so:
 _python run_summarization.py --mode=decode --data_path=/make_datafiles_for_pgn-master/output/finished_files/test* --vocab_path=/pointer-generator/finished_files/vocab --log_root=../pointer-generator/ --exp_name=pretrainedmodel --max_enc_steps=450 --max_dec_steps=200 --coverage=1 --single_pass=1_
I found ROUGE scoring had an issue with `settings.ini` file. If scoring isn't a priority, you can comment out those lines in `decode.py`.

**Comment by microLizzy** [comment]
@pruthvishetty When I ran the `python make_datafiles.py  ./stories  ./output`  command, the generated test.bin file is empty. I strictly follow the read me. So do you know what's going on here? Or maybe I did something wrong?
