### ISSUE TITLE
Decoding Error

### ISSUE THREAD

**Issue by scylla** [abisee/pointer-generator#6]
while decoding return statement in run_beam_search in beam_search.py will give Index Error when hyps array is empty

**Comment by pj-parag** [comment]
Facing same issue.

**Comment by abisee** [comment]
Now [fixed](https://github.com/abisee/pointer-generator/commit/3f4b4cfd5081e27a3b35e8dadca279cab96fd44f). 

`run_beam_search` was mistakenly returning `hyps` (current hypotheses) not `results` (finished hypotheses). As you can see [here](https://github.com/abisee/pointer-generator/blob/master/beam_search.py#L139), there is a safeguard against the eventuality that `results` is empty.

To fix this, just pull the latest version and run decode mode again. Train and eval mode are not affected, so no need to retrain.

**Comment by scylla** [comment]
Thanks!!!
