### ISSUE TITLE
Vocab file for pre-trained model

### ISSUE THREAD

**Issue by ojncwyog** [abisee/pointer-generator#75]
I find no corresponding vocab file in pre-trained files to the 50000  you may have used. The finished files from https://github.com/JafferWilson/Process-Data-of-CNN-DailyMail seems to have have a 200000 vocab file

There is "vocab_metadata.tsv" - with 50000 words; should this be used - though it does not have counts?

As vocab file important in decode would help if you please share a vocab file that went with the pretrained model.

Regards
Jayanta@Kolkata

**Comment by ojncwyog** [comment]
Ran decode and realized that 1st 50000 words of the 200000 words used
This is a great effort and gives good insight.
Thanks for your sharing.

**Comment by Adhira-Deogade** [comment]
The vocab file is obtained here: https://github.com/JafferWilson/Process-Data-of-CNN-DailyMail
in the finished files folder.!
