### ISSUE TITLE
Error while restarting the training for Coverage

### ISSUE THREAD

**Issue by learningneo** [abisee/pointer-generator#76]
Hello,

I have successfully trained the Pointer Generator model as mentioned in the Readme of the repo. But as per the documentation, when I am trying to train for coverage, I am facing below error:

NotFoundError (see above for traceback): Key seq2seq/decoder/attention_decoder/coverage/w_c not found in checkpoint
         [[Node: save/RestoreV2_19 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_19/tensor_names, save/RestoreV2_19/shape_and_slices)]]

The steps taken while restarting:
1. Kill the normal training process.
2. Restarting (using the same parameters as before) but add an additional parameter "--coverage=True" towards the end.

Any of the experienced folks here, please let me know what am I doing wrong and how to go ahead with Coverage training.

**Comment by pramod2157** [comment]
I am facing the same issue. How to retrain the model with coverage

**Comment by pramod2157** [comment]
Solution:
run_summarization with 'convert_to_coverage_model' as True. it will copy your last trained check point and initialize coverage network weights.
Then you can run run_summarization again with  'convert_to_coverage_model' as false and coverage as true.

**Comment by learningneo** [comment]
Super! Thanks a ton!
