### ISSUE TITLE
Mode must be train/eval/decode

### ISSUE THREAD

**Issue by Adityagrao** [abisee/pointer-generator#91]
` python run_summarization.py --mode=train  --data_path=../misc/finished_files/train.bin --vocab_path=../misc/finished_files/vocab --log_root=./log --exp_name=first_test
`
my command is "--mode=train"

I am getting an error as 

 tf.app.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "run_summarization.py", line 301, in main
    raise ValueError("The 'mode' flag must be one of train/eval/decode")
ValueError: The 'mode' flag must be one of train/eval/decode

**Comment by landmann** [comment]
Did you modify the code at all?

**Comment by Adityagrao** [comment]
No, I have not changed any core code, I am trying to update the code to Python 3.6 and Tensorflow 1.8,
You can find that repo on my hub

**Comment by yasersakkaf** [comment]
I hop you do it.

**Comment by leobouscarrat** [comment]
Could be link to the fact the tf.flags is not really supported in recent version of Tensorflow. It would be better to replace the tf.flag with something like argparse I suppose.

**Comment by Adityagrao** [comment]
Fixed, updated tf.app.flag to tf.flag,
thanks guys

**Comment by Adityagrao** [comment]
Fixed, Changed tf.app.flag to tf.flag

**Comment by xipuhu** [comment]
> Fixed, updated tf.app.flag to tf.flag,
> thanks guys

Hi, I get the same problem, can you tell me how to solve it more clearly?

**Comment by shivam13juna** [comment]
@xipuhu it's problem of outdated tensorflow version, I've updated code for current TF 1.12. You can see them [here](https://github.com/shivam13juna/Pointer_Generator)
